//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP3_GestionHackathon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTREPRISE
    {
        public int identreprise { get; set; }
        public string nomentreprise { get; set; }
        public string siret { get; set; }
        public string Adresse { get; set; }
    
        public virtual MEMBRE MEMBRE { get; set; }
    }
}
